# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "lemdroid-photon-ui"
primary_region = "sea"

[deploy]
  strategy = "canary"

[build]
  image = "ghcr.io/xyphyn/photon:latest"

[env]
  PUBLIC_INSTANCE_URL = "lemdro.id"
  PUBLIC_RANDOM_PLACEHOLDERS = false
  PUBLIC_SSR_ENABLED = true
  PUBLIC_MIGRATE_COOKIE = true

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

 [http_service.concurrency]
    type = "requests"
    hard_limit = 1024
    soft_limit = 768
  
  [[http_service.checks]]
    interval = "5s"
    timeout = "1s"
    grace_period = "1s"
    method = "GET"
    path = "/"
    protocol = "http"

