# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "lemdroid-voyager"
primary_region = "sea"

[deploy]
  strategy = "canary"

[build]
  image = "ghcr.io/aeharding/voyager:1.0.1"
  
[env]
  CUSTOM_LEMMY_SERVERS = "lemdro.id"

[http_service]
  internal_port = 5314
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 100
  
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "1s"
    method = "GET"
    path = "/posts/lemdro.id/local"
    protocol = "http"
